run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/jackc/pgx/v5
          - github.com/jackc/pgx/v5/pgxpool
          - github.com/kotoproger/exchange/internal/repository
          - github.com/Rhymond/go-money
          - context
          - fmt
          - os
          - sync
          - github.com/joho/godotenv
          - github.com/kotoproger/exchange/app
          - github.com/kotoproger/exchange/internal/source
          - github.com/kotoproger/exchange/internal/source/cbr
          - github.com/kotoproger/exchange/userinterface/console
          - math
          - strconv
          - time
          - github.com/kotoproger/exchange/internal/repositorywrapper
          - errors
          - testing
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/mock
          - encoding/json
          - io
          - net/http
          - net/http/httptest
          - github.com/kotoproger/exchange/userinterface
          - string
          - github.com/jackc/pgx/v5/stdlib
          - github.com/pressly/goose/v3
  funlen:
    lines: 150
    statements: 80
  govet:
    # Report about shadowed variables.
    # Default: false
    check-shadowing: true
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true

issues:
  exclude-dirs:
    - localdata
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - govet
        - lll
    - path: _test_
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - govet
        - lll
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
