// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GeneralCurrentRate struct {
	CurrencyFrom string             `db:"currency_from" json:"currency_from"`
	CurrencyTo   string             `db:"currency_to" json:"currency_to"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Rate         pgtype.Numeric     `db:"rate" json:"rate"`
}

type GeneralHistoryRate struct {
	CurrencyFrom string             `db:"currency_from" json:"currency_from"`
	CurrencyTo   string             `db:"currency_to" json:"currency_to"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Rate         pgtype.Numeric     `db:"rate" json:"rate"`
}
