// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	ArchiveRate(ctx context.Context, arg ArchiveRateParams) (*ArchiveRateRow, error)
	GetCuurentRate(ctx context.Context, arg GetCuurentRateParams) (*GetCuurentRateRow, error)
	GetRateOnDate(ctx context.Context, arg GetRateOnDateParams) (*GetRateOnDateRow, error)
	UpdateRate(ctx context.Context, arg UpdateRateParams) (*UpdateRateRow, error)
}

var _ Querier = (*Queries)(nil)
